[build]
builder = "dockerfile"
dockerfilePath = "deployment/Dockerfile"

[deploy]
startCommand = ""
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10